name: sites_management
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  dropdown_search: ^6.0.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - .env
    # - assets/rive/
    # - assets/lottie/
    # - assets/app_icon/delivery-man.png
